/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as _indexRouteImport } from './app/__index'
import { Route as ResourcesRouteImport } from './app/resources'
import { Route as AboutRouteImport } from './app/about'

const _indexRoute = _indexRouteImport.update({
  id: '/__index',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__index': typeof _indexRoute
  '/about': typeof AboutRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/resources'
  id: '__root__' | '/__index' | '/about' | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _indexRoute: typeof _indexRoute
  AboutRoute: typeof AboutRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__index': {
      id: '/__index'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _indexRoute: _indexRoute,
  AboutRoute: AboutRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
